/* Extension to generate uuid */
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

/*DWH - Create table*/
CREATE TABLE CROS_MASTER_DEBITUR
(
    ID_CROS_MASTER_DEBITUR uuid default uuid_generate_v4() not null,
    TGL_DATA               date,
    CUST_LN_CURR_KEY       int,
    COLLECT_KEY            int,
    ACCT_REGION_KEY        int,
    ACCT_KCU_KEY           int,
    CIN                    varchar(11),
    NAMA_DEBITUR           varchar(40),
    TGL_MENJADI_NASABAH    date,
    TGL_MENJADI_DEBITUR    date,
    NO_GRUP                varchar(11),
    NAMA_GRUP              varchar(40),
    SEKTOR_EKONOMI         varchar(150),
    KATEGORI_DEBITUR       varchar(10),
    KODE_KANWIL            varchar(50),
    KODE_KCU               varchar(40),
    KATEGORI_KREDIT        varchar(10),
    FLAG_HB                int,
    BALANCE_IDR            numeric(23, 2),
    HARI_TUNGGAKAN         int,
    IS_ACTIVE              boolean,
    constraint CROS_MASTER_DEBITUR_PKEY primary key (ID_CROS_MASTER_DEBITUR)
);

CREATE TABLE CROS_MASTER_KOMITMEN
(
    ID_CROS_MASTER_KOMITMEN uuid default uuid_generate_v4() not null,
    TGL_DATA                date,
    CUST_LN_CURR_KEY        int,
    ACCT_LN_CURR_KEY        int,
    COMM_CURR_KEY           int,
    PRODUCT_SUB_TYPE_KEY    int,
    FAC_LN_SEG_KEY          int,
    COLLECT_KEY             int,
    ACCT_REGION_KEY         int,
    ACCT_KCU_KEY            int,
    KODE_KANWIL             varchar(50),
    KODE_KCU                varchar(40),
    NO_REKENING_PINJAMAN    varchar(11),
    NO_KOMITMEN             varchar(6),
    TGL_BUKA_KOMITMEN       date,
    TGL_TUTUP_KOMITMEN      date,
    KATEGORI_KREDIT         varchar(10),
    TIPE_PRODUK             varchar(50),
    KODE_PRODUK             varchar(25),
    NAMA_PRODUK             varchar(100),
    MATA_UANG               char(3),
    PLAFOND_OCUR            numeric(23, 2),
    PLAFOND_IDR             numeric(23, 2),
    BALANCE_OCUR            numeric(23, 2),
    BALANCE_IDR             numeric(23, 2),
    BUNGA_OCUR              numeric(23, 2),
    BUNGA_IDR               numeric(23, 2),
    DENDA_OCUR              numeric(23, 2),
    DENDA_IDR               numeric(23, 2),
    BALANCE_OCUR_HB         numeric(23, 2),
    BALANCE_IDR_HB          numeric(23, 2),
    BUNGA_OCUR_HB           numeric(23, 2),
    BUNGA_IDR_HB            numeric(23, 2),
    DENDA_OCUR_HB           numeric(23, 2),
    DENDA_IDR_HB            numeric(23, 2),
    TGL_HB                  date,
    BALANCE_OCUR_HT         numeric(23, 2),
    BALANCE_IDR_HT          numeric(23, 2),
    BUNGA_OCUR_HT           numeric(23, 2),
    BUNGA_IDR_HT            numeric(23, 2),
    DENDA_OCUR_HT           numeric(23, 2),
    DENDA_IDR_HT            numeric(23, 2),
    TGL_HT                  date,
    PPAP                    numeric(23, 2),
    POSISI_DATA_PPAP        date,
    CKPN                    numeric(23, 2),
    POSISI_DATA_CKPN        date,
    HARI_TUNGGAKAN          int,
    IS_RESTRUKTURISASI      int,
    KODE_RESTRUKTURISASI    varchar(2),
    FLAG_HB                 int,
    constraint CROS_MASTER_KOMITMEN_PKEY primary key (ID_CROS_MASTER_KOMITMEN)
);

CREATE TABLE CROS_MASTER_PINJAMAN
(
    ID_CROS_MASTER_PINJAMAN uuid default uuid_generate_v4() not null,
    TGL_DATA                date,
    CUST_LN_CURR_KEY        int,
    ACCT_LN_CURR_KEY        int,
    COMM_CURR_KEY           int,
    LN_CURR_KEY             int,
    PRODUCT_SUB_TYPE_KEY    int,
    FAC_LN_SEG_KEY          int,
    COLLECT_KEY             int,
    ACCT_REGION_KEY         int,
    ACCT_KCU_KEY            int,
    KODE_KANWIL             varchar(50),
    KODE_KCU                varchar(40),
    NO_REKENING_PINJAMAN    varchar(11),
    NO_PINJAMAN             varchar(9),
    TGL_BUKA_PINJAMAN       date,
    TGL_TUTUP_PINJAMAN      date,
    KATEGORI_KREDIT         varchar(10),
    TIPE_PRODUK             varchar(50),
    KODE_PRODUK             varchar(25),
    NAMA_PRODUK             varchar(100),
    MATA_UANG               char(3),
    BALANCE_OCUR            numeric(23, 2),
    BALANCE_IDR             numeric(23, 2),
    BUNGA_OCUR              numeric(23, 2),
    BUNGA_IDR               numeric(23, 2),
    DENDA_OCUR              numeric(23, 2),
    DENDA_IDR               numeric(23, 2),
    BALANCE_OCUR_HB         numeric(23, 2),
    BALANCE_IDR_HB          numeric(23, 2),
    BUNGA_OCUR_HB           numeric(23, 2),
    BUNGA_IDR_HB            numeric(23, 2),
    DENDA_OCUR_HB           numeric(23, 2),
    DENDA_IDR_HB            numeric(23, 2),
    TGL_HB                  date,
    BALANCE_OCUR_HT         numeric(23, 2),
    BALANCE_IDR_HT          numeric(23, 2),
    BUNGA_OCUR_HT           numeric(23, 2),
    BUNGA_IDR_HT            numeric(23, 2),
    DENDA_OCUR_HT           numeric(23, 2),
    DENDA_IDR_HT            numeric(23, 2),
    TGL_HT                  date,
    HARI_TUNGGAKAN          int,
    IS_RESTRUKTURISASI      int,
    KODE_RESTRUKTURISASI    varchar(2),
    FLAG_HB                 int,
    constraint CROS_MASTER_PINJAMAN_PKEY primary key (ID_CROS_MASTER_PINJAMAN)
);

CREATE TABLE CROS_JAMINAN_DEBITUR
(
    ID_CROS_JAMINAN_DEBITUR   uuid default uuid_generate_v4() not null,
    TGL_DATA                  date,
    CUST_LN_CURR_KEY          int,
    COLL_CURR_KEY             int,
    NO_COLLATERAL             varchar(12),
    TIPE_JAMINAN              varchar(50),
    MATA_UANG                 char(3),
    DESKRIPSI_JAMINAN         varchar(418),
    NILAI_PASAR_OCUR          numeric(23, 2),
    NILAI_PASAR_IDR           numeric(23, 2),
    NILAI_TAKSASI_OCUR        numeric(23, 2),
    NILAI_TAKSASI_IDR         numeric(23, 2),
    NILAI_HAK_TANGGUNGAN_OCUR numeric(23, 2),
    NILAI_HAK_TANGGUNGAN_IDR  numeric(23, 2),
    NILAI_LIKUIDASI_OCUR      numeric(23, 2),
    NILAI_LIKUIDASI_IDR       numeric(23, 2),
    SOLID_NON_SOLID           varchar(9),
    TGL_BAP                   date,
    IS_ACTIVE                 boolean,
    constraint CROS_JAMINAN_DEBITUR_PKEY primary key (ID_CROS_JAMINAN_DEBITUR)
);

CREATE TABLE CROS_PEMEGANG_SAHAM
(
    ID_CROS_PEMEGANG_SAHAM     uuid default uuid_generate_v4() not null,
    TGL_DATA                   date,
    CUST_LN_CURR_KEY           int,
    NAMA_PEMEGANG_SAHAM        varchar(30),
    PENGURUS_PEMILIK_SAHAM_IND varchar(50),
    OWNER_SHARE                numeric(23, 2),
    constraint CROS_PEMEGANG_SAHAM_PKEY primary key (ID_CROS_PEMEGANG_SAHAM)
);

CREATE TABLE CROS_RELASI_JAMINAN_FASILITAS
(
    ID_CROS_RELASI_JAMINAN_FASILITAS uuid default uuid_generate_v4() not null,
    TGL_DATA                         date,
    CUST_LN_CURR_KEY                 int,
    ACCT_LN_CURR_KEY                 int,
    COMM_CURR_KEY                    int,
    COLL_CURR_KEY                    int,
    constraint CROS_RELASI_JAMINAN_FASILITAS_PKEY primary key (ID_CROS_RELASI_JAMINAN_FASILITAS)
);

CREATE TABLE CROS_NPL
(
    ID_CROS_NPL          uuid default uuid_generate_v4() not null,
    CUST_LN_CURR_KEY     int,
    ACCT_LN_CURR_KEY     int,
    COMM_CURR_KEY        int,
    PRODUCT_SUB_TYPE_KEY int,
    FAC_LN_SEG_KEY       int,
    COLLECT_KEY          int,
    CURR_KEY             int,
    ACCT_REGION_KEY      int,
    ACCT_KCU_KEY         int,
    NO_REKENING_PINJAMAN varchar(11),
    NO_KOMITMEN          varchar(6),
    TIPE_PRODUK          varchar(50),
    KODE_PRODUK          varchar(25),
    NAMA_PRODUK          varchar(100),
    NPL_DATE             date,
    NPL_BALANCE_OCUR     numeric(23, 2),
    NPL_BALANCE_IDR      numeric(23, 2),
    NPL_BUNGA_OCUR       numeric(23, 2),
    NPL_BUNGA_IDR        numeric(23, 2),
    NPL_DENDA_OCUR       numeric(23, 2),
    NPL_DENDA_IDR        numeric(23, 2),
    COL_3_DATE           date,
    COL_3_BALANCE_OCUR   numeric(23, 2),
    COL_3_BALANCE_IDR    numeric(23, 2),
    COL_3_BUNGA_OCUR     numeric(23, 2),
    COL_3_BUNGA_IDR      numeric(23, 2),
    COL_3_DENDA_OCUR     numeric(23, 2),
    COL_3_DENDA_IDR      numeric(23, 2),
    COL_4_DATE           date,
    COL_4_BALANCE_OCUR   numeric(23, 2),
    COL_4_BALANCE_IDR    numeric(23, 2),
    COL_4_BUNGA_OCUR     numeric(23, 2),
    COL_4_BUNGA_IDR      numeric(23, 2),
    COL_4_DENDA_OCUR     numeric(23, 2),
    COL_4_DENDA_IDR      numeric(23, 2),
    COL_5_DATE           date,
    COL_5_BALANCE_OCUR   numeric(23, 2),
    COL_5_BALANCE_IDR    numeric(23, 2),
    COL_5_BUNGA_OCUR     numeric(23, 2),
    COL_5_BUNGA_IDR      numeric(23, 2),
    COL_5_DENDA_OCUR     numeric(23, 2),
    COL_5_DENDA_IDR      numeric(23, 2),
    constraint CROS_NPL_PKEY primary key (ID_CROS_NPL)
);